language: node_js
node_js:
  - "13"
cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: bin
  target-branch: develop
  on:
    branch: source
